### ISSUE TITLE
HTML pages

### ISSUE THREAD

**Issue by violaberg** [SamMartin92/hackathon-team-10#27]
As a **developer** I can **create HTML pages for the site** so that **I have basic structure in place**

## Acceptance Criteria

- [ ] Home page
- [ ] Search page
- [ ] Description page
- [ ] Map

## Tasks

- [ ] Create an HTML page for the homepage that introduces users to the site
- [ ] Develop an HTML page displaying a search option of romantic destinations with basic information and links to description page
- [ ] Design an HTML page for displaying detailed information about a specific romantic destination, incorporating user reviews
- [ ]  Create an HTML file specifically designed for the interactive map page
- [ ] Create a custom HTML page for 404 errors to guide users when they encounter a page that doesn't exist
