### ISSUE TITLE
Create Django Project & App

### ISSUE THREAD

**Issue by SamMartin92** [SamMartin92/hackathon-team-10#7]
As a **developer** I can **create Django project** so that **my team can start working on it**

- [x] Install Django and required libraries
- [x] Create Django project
- [x] Create Django app
- [x] Connect database with project and Heroku
