### ISSUE TITLE
Research possible APIs to use

### ISSUE THREAD

**Issue by SamMartin92** [SamMartin92/hackathon-team-10#8]
As a **developer** I can **research available APIs** so that **I can integrate external data and enhance the app's features**

## Acceptance Criteria

- [x] Free access API and enough usage for project

## Tasks

- [x] Find possible APIs for project
- [x] Determine if the APIs provide free or trial access and evaluate any potential usage limitations
